IF DB_ID('BILETSATIS') IS NOT NULL
	BEGIN 
		ALTER DATABASE [BILETSATIS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		USE MASTER
		DROP DATABASE BILETSATIS
	END 
GO

CREATE DATABASE BILETSATIS
	ON PRIMARY (	
			NAME = 'BILETSATISDB',	
			FILENAME = 'D:\database\biletsatis_db.mdf', 
			SIZE = 50MB, 
			MAXSIZE = 1000MB, 
			FILEGROWTH=30MB
				) 
	LOG ON (
		NAME = 'BILETSATISLOG', 
		FILENAME= 'D:\database\biletsatis_log.ldf', 
		SIZE= 10MB, 
		MAXSIZE= 100MB, 
		FILEGROWTH = 20MB) 
GO

USE BILETSATIS

	CREATE TABLE IL(
		ILKODU CHAR(2) PRIMARY KEY,
		ILADI VARCHAR(20) NOT NULL
	)

GO
	
	CREATE TABLE ILCE(
		ILCEID INT IDENTITY(1,1) PRIMARY KEY,
		ILCEADI VARCHAR(20) NOT NULL,
		ILKODU CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU) ON DELETE CASCADE ON UPDATE CASCADE CONSTRAINT notNullIlceIl NOT NULL
	)

GO

	CREATE TABLE FIRMA(
		FIRMAID INT IDENTITY(1,1) PRIMARY KEY,
		FIRMAAD VARCHAR(50) NOT NULL,
		WEBADRESI VARCHAR(30) CONSTRAINT chkWebsite CHECK (WEBADRESI LIKE 'www.%.%' )  CONSTRAINT notNullFirmaWeb NOT NULL,
		FIRMAADRES VARCHAR(50) NOT NULL,
		KURULUSTARIH DATE NOT NULL,
		TELNO CHAR(10) CONSTRAINT chkTelFirma CHECK (TELNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') CONSTRAINT notNullFirmaNo NOT NULL,
		TELNO2 CHAR(10) CONSTRAINT chkTelFirma2 CHECK (TELNO2 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
		TELNO3 CHAR(10) CONSTRAINT chekTelFirma3 CHECK (TELNO3 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
		FIRMAILKODU CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU) CONSTRAINT notNullFirmaIl NOT NULL,
		FIRMAILCEKODU INT FOREIGN KEY REFERENCES ILCE(ILCEID) CONSTRAINT notNullFirmaIlce NOT NULL
	)

GO

	CREATE TABLE SUBE(
		SUBEID INT IDENTITY(1,1) PRIMARY KEY,
		SUBEAD VARCHAR(50) NOT NULL,
		SUBEADRES VARCHAR(50) NOT NULL,
		TELNO CHAR(10) CONSTRAINT chkTelSube CHECK (TELNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') CONSTRAINT notNullSubeNo NOT NULL,
		TELNO2 CHAR(10) CONSTRAINT chkTelSube2 CHECK (TELNO2 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
		TELNO3 CHAR(10) CONSTRAINT chekTelSube3 CHECK (TELNO3 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
		SUBEIL CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU) NOT NULL,
		SUBEILCE INT FOREIGN KEY REFERENCES ILCE(ILCEID) NOT NULL,
		SUBEFIRMA INT FOREIGN KEY REFERENCES FIRMA(FIRMAID) NOT NULL
	)

GO

	CREATE TABLE POZISYON(
		POZISYONID INT IDENTITY(1,1) PRIMARY KEY,
		POZISYONAD VARCHAR(20) NOT NULL
	)

GO

	CREATE TABLE PERSONEL(
		PERSONELID INT IDENTITY(1,1) PRIMARY KEY ,
		TCNO CHAR(11) UNIQUE NOT NULL,
		AD VARCHAR(20) NOT NULL,
		SOYAD VARCHAR(20) NOT NULL,
		DOGUMTARIHI DATE NOT NULL,
		CINSIYET CHAR(1) CONSTRAINT chkCinsiyetPersonel CHECK (CINSIYET='E' OR CINSIYET='K') 
														CONSTRAINT notNullCinsiyetPersonel NOT NULL, -- cinsiyet degerleri k ya da e olmalidir
		MEDENIHAL CHAR(1) CONSTRAINT chkMedeniHalPersonel CHECK (MEDENIHAL = 'E' OR MEDENIHAL= 'B') 
														  CONSTRAINT notNullMedeniPersonel NOT NULL, -- medeni hal degerleri e ya da b olmalidir
		TELEFONNO CHAR(10) CONSTRAINT chkTelPersonel CHECK (TELEFONNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
													 CONSTRAINT uniqTelPersonel UNIQUE
													 CONSTRAINT notNullPersonelTel NOT NULL,-- telefon numarasi 10 haneli olmali ve sayilardan olusmalidir
		EPOSTA VARCHAR(50) CONSTRAINT chekPostaPersonel CHECK (EPOSTA LIKE '%@%.%') 
														CONSTRAINT uniqMailPersonel UNIQUE
														CONSTRAINT notNullPersonelPosta NOT NULL,-- eposta adresinde @ isareti ve sonrasinda . olmalidir
		DOGUMIL CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU) NOT NULL,
		DOGUMILCE INT FOREIGN KEY REFERENCES ILCE(ILCEID) NOT NULL,
		POZSIYON INT FOREIGN KEY REFERENCES POZISYON(POZISYONID) NOT NULL,
		FIRMA INT FOREIGN KEY REFERENCES FIRMA(FIRMAID) NOT NULL,
		SUBE INT FOREIGN KEY REFERENCES SUBE(SUBEID) NOT NULL
		)

GO
	CREATE TABLE YOLCU(
		YOLCUID INT IDENTITY(1,1) PRIMARY KEY,
		TCNO CHAR(11) UNIQUE NOT NULL,
		AD VARCHAR(20) NOT NULL,
		SOYAD VARCHAR(20) NOT NULL,
		CINSIYET CHAR(1) CONSTRAINT yolcuCinsiyetChk CHECK (CINSIYET= 'E' OR CINSIYET = 'K') CONSTRAINT notNullYolcuCinsiyet NOT NULL,
		DOGUMTARIHI DATE NOT NULL,
		TELEFONNO CHAR(10) CONSTRAINT yolcuTelCheck CHECK (TELEFONNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
													CONSTRAINT uniqueYolcuTel UNIQUE
													CONSTRAINT notNullYolcuTel NOT NULL,
		EPOSTA CHAR(50) CONSTRAINT yolcuPostaCheck CHECK (EPOSTA LIKE '%@%.%') 
												   CONSTRAINT uniqueYolcuPosta UNIQUE
												   CONSTRAINT notNullYolcuPosta NOT NULL,
		AKTIFLIK SMALLINT DEFAULT 1 NOT NULL, -- aktifligin sonlanmasi durumunda deger 0 olarak degistirilir
		YAS AS DATEDIFF(YY,DOGUMTARIHI,GETDATE()),
		SIFRE VARCHAR(30) CONSTRAINT checkSifre CHECK( LEN(SIFRE)>=8 AND 
														SIFRE LIKE '%[0-9]%' AND
														SIFRE COLLATE Latin1_General_BIN LIKE '%[A-Z]%' AND 
														SIFRE COLLATE Latin1_General_BIN LIKE '%[a-z]%') CONSTRAINT notNullYolcu NOT NULL, 
												-- sifrede en az bir sayi,bir kucuk harf ve bir tane buyuk harf olmasi ve sifrenin 8 karakterden uzun olmasi saglanir
		--FIRMAID INT FOREIGN KEY REFERENCES FIRMA(FIRMAID) CONSTRAINT notNullYolcuFirma NOT NULL 
	)

GO

	CREATE TABLE ARACTUR(
		ARACTURID INT IDENTITY(1,1) PRIMARY KEY,
		ARACTURAD CHAR(1) NOT NULL,
	)

GO
	CREATE TABLE MARKA(
		MARKAID INT IDENTITY(1,1) PRIMARY KEY,
		MARKAAD VARCHAR(20) NOT NULL,
		ARACTURID INT FOREIGN KEY REFERENCES ARACTUR(ARACTURID)
							CONSTRAINT notNullMarkaAracTur NOT NULL
	)

GO

	CREATE TABLE ARACMODEL(
		MODELID INT IDENTITY(1,1) PRIMARY KEY,
		MODELAD VARCHAR(20) NOT NULL,
		MOTORHACMI VARCHAR(10), -- araclarda motor hacmi terimi kullanilir
		ITMEGUCU VARCHAR(10), -- ucaklarda ise jet motoru oldugu icin motor hacmi kavrami yoktur bunu yerine itki gucu kullanilir
		MOTORGUCU VARCHAR(10) NOT NULL,
		BAGAJKAPASITE VARCHAR(10) NOT NULL,
		KOLTUKSAYISI INT NOT NULL,
		MARKAID INT FOREIGN KEY REFERENCES MARKA(MARKAID)
								CONSTRAINT notNullModelMarka NOT NULL,
		ARACTURID INT FOREIGN KEY REFERENCES ARACTUR(ARACTURID)
								  CONSTRAINT notNullModelTur NOT NULL
	)

GO

	CREATE TABLE ARAC(
		ARACID INT IDENTITY(1,1) PRIMARY KEY,
		ARACTUR INT FOREIGN KEY REFERENCES ARACTUR(ARACTURID)
								CONSTRAINT notNullAracAractur NOT NULL,
		MODELID INT FOREIGN KEY REFERENCES ARACMODEL(MODELID)
								CONSTRAINT notNullAracModel NOT NULL,
		MARKAID INT FOREIGN KEY REFERENCES MARKA(MARKAID)
								CONSTRAINT notNullAracMarka NOT NULL

	)

GO
	CREATE TABLE FIRMA_ARAC(
		FIRMA_ARAC_ID INT IDENTITY(1,1) PRIMARY KEY,
		ARAC_BENZERSIZ_NO VARCHAR(10) CONSTRAINT uniqueFirmaAracNo UNIQUE 
									  CONSTRAINT notNullFirmaAracNo NOT NULL,
		ALISKM INT NOT NULL,
		GUNCELKM INT NOT NULL,
		ALISMALIYET MONEY NOT NULL,
		ALISTARIH DATE NOT NULL,
		ISKARTATARIH DATE,
		FIRMAID INT FOREIGN KEY REFERENCES FIRMA(FIRMAID) NOT NULL,
		ARACID INT FOREIGN KEY REFERENCES ARAC(ARACID)
								CONSTRAINT notNullFirmaAracArac NOT NULL
	)

GO 
	CREATE TABLE DURAKLAR(
		DURAKID INT IDENTITY(1,1) PRIMARY KEY,
		DURAKTUR CHAR(1) NOT NULL, 
		DURAKILID CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU)
									  CONSTRAINT notNullDurakIl NOT NULL,
		DURAKILCEID INT FOREIGN KEY REFERENCES ILCE(ILCEID)
									CONSTRAINT notNullDurakIlce NOT NULL
	)

GO
		
	CREATE TABLE GUZERGAH(
		GUZERGAHID INT IDENTITY(1,1) PRIMARY KEY,
		KALKISDURAK INT FOREIGN KEY REFERENCES DURAKLAR(DURAKID)
									CONSTRAINT notNullGuzergahKalkis NOT NULL,
		VARISDURAK INT FOREIGN KEY REFERENCES DURAKLAR(DURAKID)
									CONSTRAINT notNullGuzergahVaris NOT NULL
	
	)

GO
	
	CREATE TABLE SEFER(
		SEFERID INT IDENTITY(1,1) PRIMARY KEY,
		KALKISTARIH DATE NOT NULL,
		VARISTARIH DATE NOT NULL,
		FIRMA INT FOREIGN KEY REFERENCES FIRMA(FIRMAID)
							  CONSTRAINT notNullSeferFirma NOT NULL,
		SUBE INT FOREIGN KEY REFERENCES SUBE(SUBEID)
							 CONSTRAINT notNullSeferSube NOT NULL,
		GUZERGAH INT FOREIGN KEY REFERENCES GUZERGAH(GUZERGAHID)
								 CONSTRAINT notNullSeferGuzergah NOT NULL,
		KALKISDURAK INT FOREIGN KEY REFERENCES DURAKLAR(DURAKID)
									CONSTRAINT notNullSeferKalkis NOT NULL,
		KALKISSAAT TIME NOT NULL,
		VARISDURAK INT FOREIGN KEY REFERENCES DURAKLAR(DURAKID)
								   CONSTRAINT notNullSeferVaris NOT NULL,
		VARISSAAT TIME NOT NULL,
		ARAC INT FOREIGN KEY REFERENCES FIRMA_ARAC(FIRMA_ARAC_ID)
							 CONSTRAINT notNullSeferArac NOT NULL,
		ANLIKKONUM VARCHAR(20) NOT NULL
	)

GO

	CREATE TABLE SEFER_PERSONEL(
		SEFER_PERSONEL_ID INT IDENTITY(1,1) PRIMARY KEY,
		PERSONELID INT FOREIGN KEY REFERENCES PERSONEL(PERSONELID)
								   CONSTRAINT chkNullSeferPersonel NOT NULL,
		SEFER INT FOREIGN KEY REFERENCES SEFER(SEFERID)
							  CONSTRAINT chkNullSeferSefer NOT NULL
		)

GO

	CREATE TABLE UGRANILANDURAK(
		UGRANILANDURAKID INT IDENTITY(1,1) PRIMARY KEY,
		DURAKISIM VARCHAR(20) NOT NULL,
		DURAKSIRA INT NOT NULL,
		DURAKID INT FOREIGN KEY REFERENCES DURAKLAR(DURAKID)
								CONSTRAINT notNullUgranilanDurak NOT NULL,
		DURAKIL CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU)
								CONSTRAINT notNullUgranilanDurakIl NOT NULL,
		DURAKILCE INT FOREIGN KEY REFERENCES ILCE(ILCEID)
								CONSTRAINT notNullUgranilanIlce NOT NULL,
		GUZERGAHDURAK INT FOREIGN KEY REFERENCES GUZERGAH(GUZERGAHID)
									  CONSTRAINT notNullUgranilanGuzergah NOT NULL,
		SEFERDURAK INT FOREIGN KEY REFERENCES SEFER(SEFERID)
									CONSTRAINT notNullUgranilanSefer NOT NULL
	)

GO
	
	CREATE TABLE BILET(
		BILETID INT IDENTITY(1,1) PRIMARY KEY,
		UCRET MONEY NOT NULL,
		KESILMETARIH DATE NOT NULL,
		KOLTUKNO SMALLINT CONSTRAINT uniqueBiletKoltuk UNIQUE 
						  CONSTRAINT notNullBiletKoltuk NOT NULL,
		CHECKINDURUM BIT DEFAULT 0, -- 0 ya da bir olur check-in islemi yapildiysa 1 olarak ayarlanir
		CHECKINTARIH DATE,
		FIRMA INT FOREIGN KEY REFERENCES FIRMA(FIRMAID)
							  CONSTRAINT noNullBiletFirma NOT NULL,
		SUBE INT FOREIGN KEY REFERENCES SUBE(SUBEID)
							 CONSTRAINT noNullBiletSube	NOT NULL,
		BILETKESEN INT FOREIGN KEY REFERENCES PERSONEL(PERSONELID)
								   CONSTRAINT notNullBiletKesen NOT NULL,
		YOLCU INT FOREIGN KEY REFERENCES YOLCU(YOLCUID)
							  CONSTRAINT notNullBiletYolcu NOT NULL
							  CONSTRAINT chkUniqueBiletYolcu UNIQUE,
		GUZERGAH INT FOREIGN KEY REFERENCES GUZERGAH(GUZERGAHID)
							     CONSTRAINT chkNullBiletGuzergah NOT NULL,
		SEFER INT FOREIGN KEY REFERENCES SEFER(SEFERID)
							  CONSTRAINT notNullBiletSefer NOT NULL,
		BINISDURAK INT FOREIGN KEY REFERENCES UGRANILANDURAK(UGRANILANDURAKID)
								   CONSTRAINT notNullBiletBinis NOT NULL,
		INISDURAK INT FOREIGN KEY REFERENCES UGRANILANDURAK(UGRANILANDURAKID)
								  CONSTRAINT notNullBiletInis NOT NULL,
		ARAC INT FOREIGN KEY REFERENCES FIRMA_ARAC(FIRMA_ARAC_ID)
								  CONSTRAINT notNullBiletArac NOT NULL

	)