IF DB_ID('BILETSATIS') IS NOT NULL
	BEGIN 
		ALTER DATABASE [BILETSATIS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		USE MASTER
		DROP DATABASE BILETSATIS
	END 
GO

CREATE DATABASE BILETSATIS
	ON PRIMARY (	
			NAME = 'BILETSATISDB',	
			FILENAME = 'D:\database\biletsatis_db.mdf', 
			SIZE = 50MB, 
			MAXSIZE = 1000MB, 
			FILEGROWTH=30MB
				) 
	LOG ON (
		NAME = 'BILETSATISLOG', 
		FILENAME= 'D:\database\biletsatis_log.ldf', 
		SIZE= 10MB, 
		MAXSIZE= 100MB, 
		FILEGROWTH = 20MB) 
GO

USE BILETSATIS

	CREATE TABLE IL(
		ILKODU CHAR(2) PRIMARY KEY,
		ILADI VARCHAR(20) NOT NULL
	)

GO
	
	CREATE TABLE ILCE(
		ILCEID INT IDENTITY(1,1) PRIMARY KEY,
		ILCEADI VARCHAR(20) NOT NULL,
		ILKODU CHAR(2) FOREIGN KEY REFERENCES IL(ILKODU) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
	)

GO

	CREATE TABLE FIRMA(
		FIRMAID INT IDENTITY(1,1) PRIMARY KEY,
		FIRMAAD VARCHAR(20) NOT NULL,
		WEBADRESI VARCHAR(30) CONSTRAINT chkWebsite CHECK (WEBADRESI LIKE 'www.%.%' )  NOT NULL,
		FIRMAADRES VARCHAR(50) NOT NULL,
		KURULUSTARIH DATE NOT NULL,
		TELNO CHAR(10) CONSTRAINT chkTelFirma CHECK (TELNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
		TELNO2 CHAR(10) CONSTRAINT chkTelFirma2 CHECK (TELNO2 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
		TELNO3 CHAR(10) CONSTRAINT chekTelFirma3 CHECK (TELNO3 LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')

	)

GO

	CREATE TABLE PERSONEL(
		TCKIMLIKNO INT IDENTITY(1,1) PRIMARY KEY ,
		AD VARCHAR(20) NOT NULL,
		SOYAD VARCHAR(20) NOT NULL,
		DOGUMTARIHI DATE NOT NULL,
		CINSIYET CHAR(1) CONSTRAINT chkCinsiyetPersonel CHECK (CINSIYET='E' OR CINSIYET='K'), -- cinsiyet degerleri k ya da e olmalidir
		MEDENIHAL CHAR(1) CONSTRAINT chkMedeniHalPersonel CHECK (MEDENIHAL = 'E' OR MEDENIHAL= 'B'), -- medeni hal degerleri e ya da b olmalidir
		TELEFONNO CHAR(10) CONSTRAINT chkTelPersonel CHECK (TELEFONNO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') CONSTRAINT uniqTel UNIQUE,-- telefon numarasi 10 haneli olmali ve sayilardan olusmalidir
		EPOSTA VARCHAR(50) CONSTRAINT chekPostaPersonel CHECK (EPOSTA LIKE '%@%.%') CONSTRAINT uniqMail UNIQUE,-- eposta adresinde @ isareti ve sonrasinda . olmalidir
				
		)
