USE NORTHWND
SELECT * FROM Products

INSERT INTO PRODUCTS 
(PRODUCTNAME,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued)
VALUES ('deneme',1,1,'deneme kgs',20.00,20,20,20,0)

UPDATE Products
SET ReorderLevel = 0,Discontinued=1


SELECT * FROM Employees

SELECT DATEDIFF(YEAR,'1948-12-08',GETDATE())

UPDATE Employees
SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

DELETE FROM CustomerCustomerDemo

TRUNCATE TABLE CUSTOMERCUSTOMERDEMO



SELECT * FROM CUSTOMERS

WHERE ContactTitle = 'Owner'

SELECT * FROM Customers WHERE ContactTitle <> 'Owner' /* not equal */

SELECT * FROM CUSTOMERS WHERE  NOT CONTACTTITLE = 'OWNER' /* NOT EQUAL TO */

SELECT * FROM EMPLOYEES WHERE BIRTHDATE > '1960-01-01'

SELECT * FROM Employees WHERE BIRTHDATE BETWEEN  '1948-12-08' AND '1966-01-27'

SELECT * FROM Customers WHERE COMPANYNAME LIKE 'BL%'

SELECT * FROM CUSTOMERS WHERE CONTACTTITLE LIKE '%ER'

SELECT * FROM CUSTOMERS WHERE ContactName LIKE '%AN%' /* NOT LIKE */

SELECT * FROM CUSTOMERS WHERE CONTACTTITLE IN ('OWNER','SALES MANAGER')

UPDATE CUSTOMERS SET REGION = 'BILINMEYEN' WHERE REGION = 'Táchira'

SELECT * FROM CUSTOMERS WHERE REGION = 'BILINMEYEN'

SELECT * FROM Employees WHERE CITY = 'Redmond'

