USE BILETSATIS

INSERT INTO MARKA 
(MarkaAd,AracTurId)
VALUES
('mercedes', 1),
('volvo', 1),
('man', 1),
('scania', 1),
('neoplan', 1),
('iveco', 1),
('temsa', 1),
('isuzu', 1),
('ford', 1),
('van hool', 1),
('bmc', 1),
('boeing', 2),
('airbus', 2), 
('embraer', 2), 
('bombardier', 2),
('atr', 2),
('comac', 2),
('tupolev', 2),
('MSC', 3),
('carnival cruise line', 3),
('royal caribbean international', 3),
('princess cruies', 3),
('Norwegian Cruise Line',3),
('Siemens', 4),
('Bombardier Transportation', 4),
('Alstom', 4),
('hitachi rail', 4),
('stadler rail', 4),
('kawasaki heavy industries', 4),
('talgo', 4)