USE BILETSATIS

SELECT * FROM IL
SELECT * FROM ILCE
SELECT * FROM FIRMA
SELECT * FROM SUBE
SELECT * FROM POZISYON
SELECT * FROM PERSONEL
SELECT * FROM YOLCU
SELECT * FROM ARAC_TUR
SELECT * FROM MARKA
SELECT * FROM ARAC_MODEL
SELECT * FROM ARAC
SELECT * FROM FIRMA_ARAC
SELECT * FROM DURAKLAR
SELECT * FROM GUZERGAH
SELECT * FROM UGRANILAN_DURAK_GUZERGAH
SELECT * FROM SEFER
SELECT * FROM UGRANILAN_DURAK_SEFER
SELECT * FROM SEFER_PERSONEL
SELECT * FROM BILET